var car = 'subaru';
console.log("Is car == 'subaru'? I predict True.");
console.log(car == 'subaru');
console.log("is car != `honda city`? predict true");
console.log(car != "honda city");
console.log("Is car == 'subaru'? I predict false.");
console.log(car == 'subaru');
console.log("Is car == 'Subaru'? I predict false.");
console.log(car == 'Subaru');
console.log("Is car == 'SUBARU'? I predict false.");
console.log(car == 'SUBARU');
console.log("Is car == 'toyota'? I predict false.");
console.log(car == 'toyota');
console.log("Is car == 'corolla'? I predict false.");
console.log(car == 'corolla');
console.log("Is car.length == `6` ? I predict false.");
console.log(car.length == 6);
console.log("Is car.length == `10` ? I predict false.");
console.log(car.length == 10);
console.log("Is car.length != `10` ? I predict false.");
console.log(car.length != 10);
